replicaCount: 1
image:
  repository: jaimehenao8126/kubeops
  tag: 709b59fd5f72b8dfcb51c642cf88d44493a3f6c9
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: gitops1-test.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
