name: CD

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN}}
  IMAGE_NAME: kubeops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualizado a la última versión

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Actualizado a la última versión
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f ./Docker/Dockerfile ./Docker

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Helm lint
        run: helm lint ./chart

      - name: Helm template (dry-run)
        run: helm template gitops1 ./chart --set image.repository=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }},image.tag=${{ github.sha }}

      # Ejemplo de deploy (requiere kubeconfig)
      # - name: Helm upgrade --install
      #   run: helm upgrade --install gitops1 ./chart --set image.repository=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }},image.tag=${{ github.sha }}
      #   env:
      #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
